name: CI/CD for NestJS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check directory contents
        run: |
          pwd
          ls -R

      - name: ✅ Create .env file from secret
        run: |
          mkdir -p backend
          echo "${{ secrets.ENV }}" > backend/.env
          echo ".env created"
          cat backend/.env

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build project
        working-directory: ./backend
        run: npm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy build to server
        run: |
          tar -czf backend.tar.gz backend
          scp -P ${{ secrets.PORT }} backend.tar.gz ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}/backend-latest.tar.gz

      - name: Restart service via SSH
        run: |
          echo "TARGET_DIR=${{ secrets.TARGET_DIR }}"
          ssh -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} << EOF
            set -e
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            nvm use --lts
            mkdir -p ${{ secrets.TARGET_DIR }}/backend
            cd ${{ secrets.TARGET_DIR }}
            tar -xzf backend-latest.tar.gz
            ln -sfn ${{ secrets.TARGET_DIR }}/backend ${{ secrets.TARGET_DIR }}/current
            cd ${{ secrets.TARGET_DIR }}/current
            npm install --omit=dev
            npm run build
            pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app --env production
          EOF

